# Generated by Django 6.0.6 on 2026-06-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='api_match_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
