# Generated by Django 6.0.6 on 2026-06-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_api_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentstage',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
