# Generated by Django 6.0.6 on 2026-06-16 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoring', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.participant'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('participant', 'match')},
        ),
    ]
